version: '1'
services:
  redis:
    image: "redis:4"
    ports:
      - "6379:6379"
  mongodb:
    image: "mongodb:3.6"
    ports:
      - "27017:27017"
  rabbitmq-stomp:
    image: "jorgeacetozi/rabbitmq-stomp:3.6"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
